Title: Jessica Staats
logo: docs/assets/Propic.jpeg 
description: Dedicated Technical Support Specialist | Transforming Challenges into Seamless Solutions
show_downloads: true
theme: jekyll-theme-minimal
